# Generated by Django 2.2.9 on 2020-02-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_r6_f6"),
    ]

    operations = [
        migrations.CreateModel(
            name="XXX1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r1", models.BigIntegerField()),
            ],
        ),
    ]
