# Generated by Django 2.2.9 on 2020-02-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_xxx1_r111'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.BigIntegerField()),
            ],
        ),
    ]
